### ISSUE TITLE
Selecting a drifter on the map does not change the query in the address bar

### ISSUE THREAD

**Issue by erikvansebille** [samuelhklumpers/oceanparcels_website#12]
Selecting a drifter on the map does not change the query in the address bar. This means that users can't select a drifter and then share the link with that drifter selected with others

**Comment by samuelhklumpers** [comment]
The export button was added for this purpose and redirects to the url+query, it could be changed to copy to clipboard directly (without reloading).

Updating the url without reloading is possible, but this makes next/previous page a little weird as it replaces the url in the browser history too.

Let me know if the export button suffices, or which resolution or combination is best.

**Comment by erikvansebille** [comment]
I'm not sure that the meaning of 'export' will be obvious to most users (I initially thought it was to export the trajectories to a file for download?). As I said, I think it's much more intuitive to directly update the url when users click on the drifter, so that they can then share it without having to click another button. 
But perhaps we can further discuss this on Monday, during our meeting then?
