### ISSUE TITLE
Overlapping datestring and buttons on small screesn

### ISSUE THREAD

**Issue by erikvansebille** [samuelhklumpers/oceanparcels_website#19]
For relatively (not even super)small screens, the datestring and the top-left buttons overlap, see screenshot. Can that be fixed?
<img width="618" alt="Screen Shot 2021-03-19 at 17 00 44" src="https://user-images.githubusercontent.com/14315062/111808947-c5541b80-88d4-11eb-9d8a-2294ecf56b4b.png">

**Comment by samuelhklumpers** [comment]
small hack necessary because it is impractical to insert the date in the same div as the buttons (which OSM generates).
for now I'll just move the container of the buttons down
![image](https://user-images.githubusercontent.com/34067057/112211421-2acd4280-8c1c-11eb-9988-40ac5ac34d5d.png)
