### ISSUE TITLE
Test implementing in iframe

### ISSUE THREAD

**Issue by erikvansebille** [samuelhklumpers/oceanparcels_website#3]
Eventually, it would be nice if the page also works in an iframe and ideally even within the https://galapagosplasticfree.nl/ wordpress site (including queries)

**Comment by samuelhklumpers** [comment]
wordpress removes <iframe> tags from html, so a plugin like https://nl.wordpress.org/plugins/iframe/ will be necessary

**Comment by samuelhklumpers** [comment]
I think not using history.replaceState and 19ef4dcc59aef1d1e495778eb905530de0452156 resolves this
