### ISSUE TITLE
Select a specific drifter by clicking on it

### ISSUE THREAD

**Issue by erikvansebille** [samuelhklumpers/oceanparcels_website#4]
Drifters can now only be selected by altering the query in the address bar. It's important that this can also be done through clicking on the drifter (and/or its track)

**Comment by samuelhklumpers** [comment]
Clicking a drifter should open a tooltip with a clickable link to select it, unless this doesn't work or is undesirable I will close this issue

**Comment by samuelhklumpers** [comment]
I ignore clicks on the track for now because that makes the tooltip show up in odd places, but that could be re-enabled if neccessary

**Comment by erikvansebille** [comment]
Ah, I did not realise that. I think I'd prefer it if, when clicking a drifter, it opens the tooltip _and_ highlights it immediately. Is that possible to implement?

**Comment by samuelhklumpers** [comment]
Will try to implement this along with #9
